apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.12.0
patches:
- path: patches/argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argo-cm
